/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulaRouteImport } from './routes/aula'
import { Route as AulaOfferRouteImport } from './routes/aula-offer'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as GuiaObrigadoRouteImport } from './routes/guia.obrigado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaRoute = AulaRouteImport.update({
  id: '/aula',
  path: '/aula',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaOfferRoute = AulaOfferRouteImport.update({
  id: '/aula-offer',
  path: '/aula-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaObrigadoRoute = GuiaObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => GuiaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aula': typeof AulaRoute
  '/aula-offer': typeof AulaOfferRoute
  '/guia': typeof GuiaRouteWithChildren
  '/oferta': typeof OfertaRoute
  '/guia/obrigado': typeof GuiaObrigadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aula': typeof AulaRoute
  '/aula-offer': typeof AulaOfferRoute
  '/guia': typeof GuiaRouteWithChildren
  '/oferta': typeof OfertaRoute
  '/guia/obrigado': typeof GuiaObrigadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aula': typeof AulaRoute
  '/aula-offer': typeof AulaOfferRoute
  '/guia': typeof GuiaRouteWithChildren
  '/oferta': typeof OfertaRoute
  '/guia/obrigado': typeof GuiaObrigadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/aula' | '/aula-offer' | '/guia' | '/oferta' | '/guia/obrigado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aula' | '/aula-offer' | '/guia' | '/oferta' | '/guia/obrigado'
  id:
    | '__root__'
    | '/'
    | '/aula'
    | '/aula-offer'
    | '/guia'
    | '/oferta'
    | '/guia/obrigado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulaRoute: typeof AulaRoute
  AulaOfferRoute: typeof AulaOfferRoute
  GuiaRoute: typeof GuiaRouteWithChildren
  OfertaRoute: typeof OfertaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula': {
      id: '/aula'
      path: '/aula'
      fullPath: '/aula'
      preLoaderRoute: typeof AulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-offer': {
      id: '/aula-offer'
      path: '/aula-offer'
      fullPath: '/aula-offer'
      preLoaderRoute: typeof AulaOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/obrigado': {
      id: '/guia/obrigado'
      path: '/obrigado'
      fullPath: '/guia/obrigado'
      preLoaderRoute: typeof GuiaObrigadoRouteImport
      parentRoute: typeof GuiaRoute
    }
  }
}

interface GuiaRouteChildren {
  GuiaObrigadoRoute: typeof GuiaObrigadoRoute
}

const GuiaRouteChildren: GuiaRouteChildren = {
  GuiaObrigadoRoute: GuiaObrigadoRoute,
}

const GuiaRouteWithChildren = GuiaRoute._addFileChildren(GuiaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulaRoute: AulaRoute,
  AulaOfferRoute: AulaOfferRoute,
  GuiaRoute: GuiaRouteWithChildren,
  OfertaRoute: OfertaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
