// Extraído de /oferta para ser carregado sob demanda (só é necessário se a
// visitante abrir o modal de order bump).
import { BookOpen, CircleCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { offerConfig } from "@/config/offers";
import { goToCheckout, trackEvent } from "@/lib/tracking";

export default function OrderBumpModal({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto rounded-2xl border-primary/20 p-7 md:p-9"><div className="mx-auto grid size-14 place-items-center rounded-full bg-secondary text-primary"><BookOpen className="size-7" /></div><DialogTitle className="text-center text-2xl font-extrabold leading-tight text-plum">{offerConfig.orderBump.title}</DialogTitle><DialogDescription className="text-center text-base leading-relaxed">Antes de continuar, adicione este material objetivo ao seu Plano Completo.</DialogDescription><div className="rounded-2xl border border-primary/20 bg-secondary p-5"><p className="text-center text-lg font-extrabold leading-snug text-plum">{offerConfig.orderBump.name}</p><p className="mt-3 text-center text-4xl font-extrabold text-primary">R$ {offerConfig.orderBump.price},00</p></div><p className="flex gap-3 text-sm leading-relaxed text-muted-foreground"><CircleCheck className="mt-0.5 size-5 shrink-0 text-primary" />Leve perguntas essenciais organizadas para conversar com seu obstetra com mais clareza.</p><Button className="min-h-14 whitespace-normal rounded-2xl bg-accent text-accent-foreground font-extrabold hover:bg-accent/90" onClick={() => { trackEvent("order_bump_accepted", { product: "guia_18_perguntas", price: 27 }); goToCheckout(offerConfig.orderBump.checkoutUrl, "complete_with_guide"); }}>SIM, QUERO ADICIONAR O GUIA POR R$ 27</Button><DialogClose asChild><Button variant="link" className="h-auto whitespace-normal text-sm text-muted-foreground" onClick={() => { trackEvent("order_bump_declined", { product: "guia_18_perguntas" }); goToCheckout(offerConfig.complete.checkoutUrl, "complete"); }}>Não, obrigada. Continuar somente com o Plano Completo</Button></DialogClose></DialogContent></Dialog>;
}
